### ISSUE TITLE
Possible typo in Guide.md

### ISSUE THREAD

**Issue by marcino239** [samjabrahams/tensorflow-on-raspberry-pi#16]
Looks like there is a typo in the line in file [Guide.md](https://github.com/samjabrahams/tensorflow-on-raspberry-pi/blob/master/GUIDE.md)
git checkout d5fb408d

I think it should be:
git checkout d5fb408d **.**

**Comment by samjabrahams** [comment]
Thanks for opening this up! The original command is actually correct in this scenario.

* `git checkout <commit>` without a path specified will move the HEAD to that commit, effectively moving us back in time to that commit. 

* `git checkout <commit> <path>` will not move the HEAD, but modify all files needed to simulate the commit and stages those changes.

Although the result of both of these commands leads to identical file/directory contents, the status of the HEAD and staging area is drastically different. The first leaves the staging area clean, while the second fills it with all changes needed to revert the files to their previous state. Since we aren't looking to commit/revert these changes to master, it's better to simply checkout the old commit.

As an exercise, try running `git checkout d5fb408d .` in the Protobuf repository, and then try to get the working directory back to being clean again. If you simply run `git checkout .` (after unstaging the changes), you'll notice that there are several files that are no longer tracked and will have to be removed manually. In contrast, if you run `git checkout d5fb408d`, you are able to use the command `git checkout master` to get back to the original state.

I appreciate you double checking this, though!
