### ISSUE TITLE
TensorFlow has question about google cloud platform support

### ISSUE THREAD

**Issue by pageauc** [samjabrahams/tensorflow-on-raspberry-pi#19]
I have been working my way through your excellent install instructions.  At TensorFlow ./configure there is an extra question that is not documented

    Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] N

I was not sure so I answered N.  Currently the compile is underway with no issues yet.  Can you explain the cloud platform support configuration option. 
My aim is to install magenta and possibly music21 and do some learning about the various capabilities.  Running this on a RPI3 with latest Jessie so no real issues so far.  I originally tried it using Jessie Lite but had quite a few problems so decided to use the full Jessie and so far your instructions work perfectly.

Thanks Claude

**Comment by samjabrahams** [comment]
Oh, good catch! In general, "No" is the correct response for typical builds. Recently, Google released a limited preview of it's [machine learning service on the Google Cloud Platform](https://cloud.google.com/ml/), which uses TensorFlow as the computation engine. Building with Google Cloud Support enables certain APIs to be included, but since it's only available to those who are admitted into the limited preview, it's not necessary for most people.

I'll add instructions about this to the guide to address this issue. Thanks for bringing it up!

**Comment by samjabrahams** [comment]
Should be taken care of with 3cc3aacecb88bf6b137

**Comment by ClaudioCimarelli** [comment]
Hello @samjabrahams, do you know if it is possible to avoid compiling such feature of Google Cloud with TF 1.12? There is not an option while doing `./configure` with this release version, and I am experiencing issues related with Google Cloud source code during the build.
Thanks.
