### ISSUE TITLE
Update to 0.9

### ISSUE THREAD

**Issue by SebastianBoyd** [samjabrahams/tensorflow-on-raspberry-pi#21]
the current stable tensorflow version is 0.9

**Comment by MrSlayer02** [comment]
Yes, but you can still build it like before, follow the GUIDE.md !

**Comment by samjabrahams** [comment]
Thanks @SebastianBoyd and @MrSlayer02  - I'm going to wait until the 0.9 release candidate becomes an official release before updating the binaries in this repository. If you check out the [release notes](https://github.com/tensorflow/tensorflow/releases/tag/v0.9.0rc0), you'll see that it's currently "pre-release".

It looks like there may be some tweaks that need to be made to GUIDE.md to have everything work smoothly, so I'll make sure that to go through the entire process to make sure things are up to date.

**Comment by MrSlayer02** [comment]
Actually it seems not to be possible to install `TensorFlow 0.9` without CUDA, because half floats are used even if you configure without GPU support. Raspberry Pi does not supports CUDA, so installing 0.9 will require source code edit to remove all half floats uses.

**Comment by samjabrahams** [comment]
It looks like the issue has to do with the Neon instruction flag- the Eigen 16-bit floating point doesn't play nice with Neon, it would seem.

If you still want to build it yourself, try again without the `--copt="-mfpu=neon"` flag. If you just want 0.9rc0, I'm uploading the binary now!

**Comment by samjabrahams** [comment]
I made a [pre-release](https://github.com/samjabrahams/tensorflow-on-raspberry-pi/releases/tag/v0.9.0rc0) to match up with the 0.9rc0 binaries available on the official TensorFlow repo.

In the future, my plan is to only release Raspberry Pi binaries once a release candidate goes gold due to time constraints on my end. However, working through the issue #20 caused me to end up with 0.9rc0 binaries anyway, so I figured I may as well put them out there. Python 3 binaries are currently compiling :)
