### ISSUE TITLE
Error in v0.9 using python3.x

### ISSUE THREAD

**Issue by eyewy** [samjabrahams/tensorflow-on-raspberry-pi#29]
When I use python3.4, I get the following error:

> > > import tensorflow as tf
> > > RuntimeError: module compiled against API version 0xa but this version of numpy is 0x9

I don't get the error using python2.7

**Comment by samjabrahams** [comment]
Thanks for opening this up! Very weird- I'll check this out as soon as I get the chance.

**Comment by shrimpwonton** [comment]
Tensorflow 0.9.0 is also giving the wrong classification with python 2.7:

> window screen (score = 0.05178)

**Comment by shrimpwonton** [comment]
Tensorflow 0.9.0 is also giving the wrong classification with python 2.7:

> window screen (score = 0.05178)
web site, website, internet site, site (score = 0.02289)
honeycomb (score = 0.01543)
window shade (score = 0.01286)
nematode, nematode worm, roundworm (score = 0.00703)
Build graph time: 3.489147
Eval time: 9.210417

It seems to be an error with how the image is being processed since the classifications indicate that it may be reading in a blank white screen or something like that.

**Comment by shrimpwonton** [comment]
v0.9 also has the same classification error with python 3.4

**Comment by zxzhijia** [comment]
@shrimpwonton Did you also trained it on Raspberry Pi?

**Comment by shrimpwonton** [comment]
@zxzhijia no, I used the example in this repo (in benchmarks/inceptionv3). It also gives the same error if I use the file in the tensorflow python package

**Comment by zxzhijia** [comment]
Ok, then I'm not sure what's going on. Sorry about that.

**Comment by samjabrahams** [comment]
I'll be looking into this. I had to change some of the compiler flags for floating point variables in 0.9 due to the use of Eigen::half inside of TensorFlow, but I'm not sure if that would cause straight up miscalculations by itself.

**Comment by samjabrahams** [comment]
Hey all- not sure if this is going to be a fix or not, but I found that some of the changes introduced in the official repository related to specifying the platform for compilation may have messed up some functionality. Recompiling the binaries tonight/tomorrow and will try to see if it helps out with any of these errors.

Copied from #31:

> If you're interested in the details (at least what I'm pretty sure is going on): Essentially, [these lines](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/platform.h#L40-L45) are causing the compilation to target the Raspberry Pi as a mobile device, which in turn causes no 64-bit floating points to be registered for any Ops [in this file](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/register_types.h#L107-L131). The current hack-y fix is to delete [this line](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/platform.h#L45). If that works, I'll try to get a fix introduced into the official repository that is a bit more robust.

**Comment by samjabrahams** [comment]
@eyewy It's possible that the version of NumPy installed on your Raspberry Pi is simply the wrong version due to another package you've installed. You can either try creating a Virtualenv and reinstalling TensorFlow (as described [here](https://www.tensorflow.org/versions/master/get_started/os_setup.html#virtualenv-installation), just install the RPi binaries instead of the official binaries), or you can try `pip uninstall numpy` or `pip3 uninstall numpy` before reinstalling the TensorFlow binaries.

@shrimpwonton I'm still testing these, but I've updated these binaries in response to the aforementioned changes. Let me know if the classification error is still messed up for you- it works on my end with these guys.

Python2.7: https://github.com/samjabrahams/tensorflow-on-raspberry-pi/raw/master/bin/tensorflow-0.9.0-cp27-none-linux_armv7l.whl

Python3: https://github.com/samjabrahams/tensorflow-on-raspberry-pi/raw/master/bin/tensorflow-0.9.0-py3-none-any.whl

**Comment by shrimpwonton** [comment]
@samjabrahams it seems to be working now, thanks!

**Comment by samjabrahams** [comment]
@eyewy any status updates on your end?

**Comment by eyewy** [comment]
I get the following NumPy version error:
RuntimeError: module compiled against API version 0xa but this version of numpy is 0x9

**Comment by samjabrahams** [comment]
Is this after uninstalling numpy and then reinstalling TensorFlow (or using virtualenv)?

**Comment by samjabrahams** [comment]
Closing this issue for now- @eyewy let me know if you're still experiencing issues.
