### ISSUE TITLE
Why pi needs so many time?

### ISSUE THREAD

**Issue by alephman** [samjabrahams/tensorflow-on-raspberry-pi#38]
Hi,
 In this link( https://github.com/samjabrahams/tensorflow-on-raspberry-pi/tree/master/benchmarks/inceptionv3), it lists the pi's Inception-v3 speed data. I have tried to install the android demo(https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android) on my android cell phone, it can complete a picture recognition only around 3sec.   I don't thank my samsung S6's hardware without GPU is much faster than pi. I am really curious about that!

**Comment by samjabrahams** [comment]
Hi @alephman - I still need to do specific tests, but I believe that the issue has to do with limited RAM, converting 64-bit operations to 32-bit (Raspbian is 32-bit operating system), and/or data transfer speeds. Sorry for the delayed response: lots of work going on.

**Comment by samjabrahams** [comment]
Just to make a note on this: it turns out that the main culprit in the benchmark is that TensorFlow performs optimizations on-the-fly as you use a model. That is, the first time you load up a graph and run it, it is much slower than subsequent runs. In order to get comparable speed, you need to keep a Session alive in the background instead of loading up a separate Session each time you want to make a run.

I updated [the benchmarks](https://github.com/samjabrahams/tensorflow-on-raspberry-pi/tree/master/benchmarks/inceptionv3) at the beginning of December- sorry for the delay in responding to this.
