### ISSUE TITLE
tensorflow-on-raspberry-pi: What (exact) version of Raspbian Jessie?

### ISSUE THREAD

**Issue by avantol** [samjabrahams/tensorflow-on-raspberry-pi#73]
### Describe the Issue

Exact version of Raspbian Jessie to use is not described.

I've run into problems getting the .whl file to complete error-free (will leave the details out for now)

I think I should use the exact version of Raspbian Jessie you used, before entering an issue.

What is the Raspbian Jessie *version* (by date, like "January 2017", as seen at the download page):
https://www.raspberrypi.org/downloads/raspbian/ 

Thanks!!!!

### Steps to Reproduce

n/a

### Hardware/Software Info

n/a

**Comment by samjabrahams** [comment]
I can't remember the exact date I used for the build process. From [this list](http://downloads.raspberrypi.org/raspbian/release_notes.txt), my guess is that I've currently got it to work using the 2016-09-23 release.

Next time I build a version from scratch, I'll use whatever the latest version of Raspbian is and make a note of the release date in the README.

Open up an issue with your specific problem, though- I'd be surprised if the error you're seeing is due to the specific sub-version of Jessie.

**Comment by samjabrahams** [comment]
I've added exact information to both the README and release page for the most recent binaries.
