### ISSUE TITLE
Question (Not issue): Difference from the main tensorflow project?

### ISSUE THREAD

**Issue by rahulraj80** [samjabrahams/tensorflow-on-raspberry-pi#93]
Hi,

A *COMPLETE* Raspberry NewBie here, but this project was the top hit when I wanted to install TensorFlow on my RaspBerry Pi 3 Model B, hence here goes:

What is the difference in the final tensorflow/ tensorboard app we get from this fork vs the main tensorflow page if we follow the guide (https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile#raspberry-pi).

Asking because the other build compiled and installed quickly but I ran into some issues and hence was reinstalling from scratch when I ran into this guide (https://github.com/samjabrahams/tensorflow-on-raspberry-pi/blob/master/GUIDE.md#the-build) which I am following right now.

While the bazel is building, I thought I would ask experienced hands about the difference. Also, the next step suggests that it would take hours to build tensorflow after Bazel gets built, so will this binary/ application be any different from the first one?

I am not sure, how to tag this as a question, but I can see in the Issue list that a few cases are tagged as Question. Can someone guide me please?

**Comment by samjabrahams** [comment]
Hi @rahulraj80 - that's a really good question. The main difference is that this repository builds the complete Python bindings instead of a static C++ library. [At the top of the Makefile README, you'll find this quote]:(https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile#tensorflow-makefile)

>The recommended way to build TensorFlow from source is using the Bazel
open-source build system. Sometimes this isn't possible. For example,
if you are building for iOS, you currently need to use the Makefile.
>
>- The build system may not have the RAM or processing power to support Bazel.
> - Bazel or its dependencies may not be available.
>- You may want to cross-compile for an unsupported target system.
>
>This experimental project supplies a Makefile automatically derived from the
dependencies listed in the Bazel project that can be used with GNU's make tool.
With it, you can compile the core C++ runtime into a static library.
>
>This static library will not contain:
>
>- Python or other language bindings
>- GPU support

This repository contains instructions to compile the standard TensorFlow Python library targeted for the Raspberry Pi using Bazel. We also have [pre-compiled binaries](https://github.com/samjabrahams/tensorflow-on-raspberry-pi/releases) if you're building for Python 2.7 or 3.4 and just want a vanilla installation of an official TensorFlow release.

Here are the plusses from this repo:

- Simpler to use for people who either don't know C++
- Easier to port a TensorFlow program from a desktop/VM to the Raspberry Pi (don't need to recompile the program)
- Makes it easier to use existing Python libraries with your TensorFlow program on the Pi (such as [RPIO](https://pythonhosted.org/RPIO/))

There is still room for this repository to grow, however:

- The biggest downside is that this repository is slow compared to using a static C++ TensorFlow library. For example, InceptionV3 takes about ~2 seconds to run with the Python library as opposed to ~0.5-0.6 seconds using C++.
- This repo isn't officially supported by the TensorFlow team, so we're on our own when things start going haywire or breaking changes occur. Granted, there are several Googlers who are aware of this project, and they have been incredibly helpful in keeping things running relatively smoothly on our end.

Let me know if you have any more questions!

**Comment by rahulraj80** [comment]
Thanks for clarifying. I missed the header on the makefile :")
